# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 094663702f9d55748a15378331e4baa18873a7b75cf6b2573f660e38316899b2993bbe8712c09dc811cc8e088c854c69d6ad30f01a492ba53514277ef25c30ab

test:
  secret_key_base: d3788a750cc07c7bafffb836c6c7d439ff56d0551d12058761268f2cf246d7a1d2be97a17a09773630acccfe764ef8af9835d7d5a96f02262a857c7b14291087

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
